services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/hoohacks2025
      - API_KEY=HwTLmOnfitsTqOzS0e7RO9g5EoKWe3f7
      - API_SECRET=fD4Kc5Zr0gPkM7bt
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
